# Generated by Django 2.2.5 on 2019-12-14 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='カテゴリー名')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='商品名')),
                ('price', models.PositiveIntegerField(verbose_name='価格')),
                ('ec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ec.Ec')),
            ],
        ),
    ]
